;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        back-to-indentation-or-beginning
        c-electric-semi&comma
        select-symbol-under-cursor
        smarter-move-beginning-of-line
        ))

(setq mc/cmds-to-run-once
      '(
        yas-expand
        ))
